modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="projecdz"
version="1.0.0"
displayName="projectDZ"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="dZ, MCreator"

[[dependencies.projecdz]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




